.class public Lcom/autolink/adaptermanager/car/CarVehicleControlPropConfig;
.super Ljava/lang/Object;
.source "CarVehicleControlPropConfig.java"


# static fields
.field static final HAL_AREAID_VC_VENDOR_ADAS_AEB_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_AEB_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_BSD_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_BSD_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_DAI_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_DAI_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_DAI_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_DOW_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_DOW_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_DWD_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_DWD_WARNING_DISTANCE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_DWD_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_ELK_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_ELK_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_ELK_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_FCW_ON_OFF_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_FCW_ON_OFF_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_FCW_SEN_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_FCW_SEN_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_IES_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_IES_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_IES_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_IF_EXIT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_IF_EXIT_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_IF_EXIT_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDP_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDP_SEN_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDP_SEN_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDP_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDP_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDW_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDW_WARN_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDW_WARN_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDW_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_LDW_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_RCW_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_RCW_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_SCF_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_SCF_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_SLA_ON_OFF_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_SLA_ON_OFF_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_TLI_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_TLI_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_TSI_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ADAS_TSI_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AEB_DEC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AEB_T1P_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AEB_T1P_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ATMOSPHERE_LIGHT_BRIGHTNESS_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ATMOSPHERE_LIGHT_BRIGHTNESS_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ATMOSPHERE_LIGHT_COLOR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ATMOSPHERE_LIGHT_COLOR_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ATMOSPHERE_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ATMOSPHERE_LIGHT_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AUTOLOCK_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AUTOLOCK_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AUTOUNLOCK_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AUTOUNLOCK_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AVH_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_AVH_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_BLINK_NO_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_BLINK_NO_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_BRAKE_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CHILD_LOCK_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CHILD_LOCK_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_AIRBAG_FAIL_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_APA_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_AVM_ATCM_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_AVM_REQ_RESULT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_HAZARD_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_LATERA_ACCALELERATION_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_LH_TURN_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_LONGITUDINAL_ACCALELERATION_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_RH_TURN_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CLUSTER_TAIL_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_COOL_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CURVE_DEC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_CURVE_DEC_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DCLC_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DCLC_ZDC_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DISTANCE_WARNING_T1P_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DISTANCE_WARNING_T1P_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DISTRACTION_LEVEL_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DMS_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DMS_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_LUMBART_FR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_LUMBART_FR_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_LUMBART_UD_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_LUMBART_UD_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_SEATF_UD_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_SEATF_UD_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_SEATR_UD_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_SEATR_UD_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_SEAT_BACK_FR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_SEAT_BACK_FR_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_SEAT_FR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVER_SEAT_FR_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVE_MODE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_DRIVE_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_EPS_DRIVER_MODE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_EPS_DRIVER_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_EPS_MODE_PHEV_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_EPS_MODE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_EPS_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ESP_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ESP_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FATIGUE_DRIVE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FCW_ON_T1P_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FCW_ON_T1P_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FCW_OPTION_T1P_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FCW_OPTION_T1P_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FL_WINDOW_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FL_WINDOW_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FOLLOW_ME_HOME_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FOLLOW_ME_HOME_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FR_WINDOW_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_FR_WINDOW_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_HDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_HDC_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_HIGH_BEAM_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_HMA_ON_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_HMA_ON_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_HMA_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_HMA_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ISS_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_ISS_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_KEY_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_LDW_SEN_T1P_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_LDW_SEN_T1P_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_LDW_T1P_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_LDW_T1P_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_LH_TURN_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_LIGHT_HEIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_LIGHT_HEIGHT_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_LOW_BEAM_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MFS_HEAT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MFS_HEAT_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MFS_SHAKE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MFS_SHAKE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_DRIVER_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_DRIVER_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_FLIP_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_FLIP_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_HOLD_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_HOLD_SWITCH_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_HOLD_SWITCH_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_HOLD_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_LEFT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_LEFT_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_RIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MIRROR_RIGHT_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_LOUDNESS_1000HZ_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_LOUDNESS_120HZ_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_LOUDNESS_1500HZ_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_LOUDNESS_2000HZ_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_LOUDNESS_250HZ_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_LOUDNESS_500HZ_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_LOUDNESS_6000HZ_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_MUSIC_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_MASSAGE_INTENSITY_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_MASSAGE_INTENSITY_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_MASSAGE_MODE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_MASSAGE_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_MASSAGE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_MASSAGE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_MIRROR_LOCATION_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_MIRROR_LOCATION_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_SEAT_BACK_FR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_SEAT_BACK_FR_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_SEAT_FR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_SEAT_FR_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_SEAT_LEG_FR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PASSENGER_SEAT_LEG_FR_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PAS_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PAS_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PAS_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PAS_ZDC_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PHEV_HV_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PHEV_POWER_DISTANCEREAD:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PHEV_POWER_MODE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PHEV_POWER_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PHEV_PT_READY_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PHEV_REGEBERATE_LEVEL_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_PHEV_REGEBERATE_LEVEL_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_POWER_ALARM_MODE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RCTB_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RCTB_ZDC_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RCW_ZDC_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RCW_ZDC_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_REAR_WIPER_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_REAR_WIPER_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_REMOTELOCK_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_REMOTELOCK_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RH_TURN_LIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RL_WINDOW_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RL_WINDOW_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RR_WINDOW_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_RR_WINDOW_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_CO_ERR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_CO_STS_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_DRIVER_DOOR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_EMS_ENGINE_STS_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_ENGINE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_KEY_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_LIGHT_SHOW_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_LR_DOOR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_PASSENGER_DOOR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_PM25_STS_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_POWER_LIMIT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_RANDOM_SHOW_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_RR_DOOR_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_SHOW_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SCENE_SMART_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SKYLIGHT_PERCENTAGE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SKYLIGHT_PERCENTAGE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SKYLIGHT_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SKYLIGHT_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SLA_T1P_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SLA_T1P_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SOC_MANAGE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SOC_MANAGE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_STATIC_MODE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_STATIC_MODE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_STEER_ANGLE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SUNSHADE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_SUNSHADE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_TIRE_LF_PRESSURE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_TIRE_LR_PRESSURE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_TIRE_POSTION_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_TIRE_RF_PRESSURE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_TIRE_RR_PRESSURE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_TIRE_TEMPERATURE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_TJA_T1P_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_TJA_T1P_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_USER_ID_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_VOICE_WAKE_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_WELCOME_FL_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_WELCOME_FL_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_WELCOME_PASSENGER_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_WELCOME_PASSENGER_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_WELCOME_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_WELCOME_WRITE:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_WIRELESS_CHARGING_STS_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_WIRELESS_ENTER_SFCHARGE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_X_MODE_READ:I = 0x0

.field static final HAL_AREAID_VC_VENDOR_X_MODE_WRITE:I = 0x0

.field static final HAL_PROPID_ACC_MODE_CR2407_READ:I = 0x2140082f

.field static final HAL_PROPID_ACC_MODE_READ:I = 0x214002bc

.field static final HAL_PROPID_AEB_MODE_CR2407_READ:I = 0x21400832

.field static final HAL_PROPID_AEB_MODE_READ:I = 0x21400819

.field static final HAL_PROPID_AMP_SOUND_EFFECT_BASSMIDTREBLE_READ:I = 0x21401241

.field static final HAL_PROPID_AMP_SOUND_EFFECT_BASSMIDTREBLE_WRITE:I = 0x21401240

.field static final HAL_PROPID_AMP_SOUND_EFFECT_BASSMID_READ:I = 0x2140123f

.field static final HAL_PROPID_AMP_SOUND_EFFECT_BASSMID_WRITE:I = 0x2140123e

.field static final HAL_PROPID_BLUETOOTH_DISPLAY_READ:I = 0x214005aa

.field static final HAL_PROPID_BSD_MODE_READ:I = 0x2140081c

.field static final HAL_PROPID_CST_SEN_READ:I = 0x2140058e

.field static final HAL_PROPID_CST_SEN_WRITE:I = 0x2140058d

.field static final HAL_PROPID_DAS_DISPLAY_READ:I = 0x214005ac

.field static final HAL_PROPID_DOOR_KNOB_MODE_READ:I = 0x2140059e

.field static final HAL_PROPID_DOOR_KNOB_MODE_WRITE:I = 0x2140059d

.field static final HAL_PROPID_DOOR_KNOB_TIME_READ:I = 0x2140059c

.field static final HAL_PROPID_DOOR_KNOB_TIME_WRITE:I = 0x2140059b

.field static final HAL_PROPID_DRIVER_UNLOCK_READ:I = 0x214004c5

.field static final HAL_PROPID_DRIVER_UNLOCK_WRITE:I = 0x2140048c

.field static final HAL_PROPID_DRIVE_ATMOSPHERE_LIGHT_READ:I = 0x21400592

.field static final HAL_PROPID_DRIVE_ATMOSPHERE_LIGHT_WRITE:I = 0x21400591

.field static final HAL_PROPID_DVR_IHU_DATA0_T1L_READ:I = 0x214005b9

.field static final HAL_PROPID_DVR_IHU_DATA1_T1L_READ:I = 0x214005ba

.field static final HAL_PROPID_DVR_IHU_DATA2_T1L_READ:I = 0x214005bb

.field static final HAL_PROPID_DVR_IHU_DATA3_T1L_READ:I = 0x214005bc

.field static final HAL_PROPID_DVR_IHU_DATA4_T1L_READ:I = 0x214005bd

.field static final HAL_PROPID_DVR_IHU_DATA5_T1L_READ:I = 0x214005be

.field static final HAL_PROPID_DVR_IHU_DATA6_T1L_READ:I = 0x214005bf

.field static final HAL_PROPID_DVR_IHU_DATA7_T1L_READ:I = 0x214005c0

.field static final HAL_PROPID_DVR_IHU_SYSTEMSTS_T1L_READ:I = 0x214005c1

.field static final HAL_PROPID_EPB_AUTO_READ:I = 0x214004e9

.field static final HAL_PROPID_EPB_AUTO_WRITE:I = 0x214004e8

.field static final HAL_PROPID_EPB_READ:I = 0x214004e7

.field static final HAL_PROPID_EPB_WRITE:I = 0x214004e6

.field static final HAL_PROPID_FCM_10_SLA_ONOFF_READ:I = 0x2140081d

.field static final HAL_PROPID_HAZARD_READ:I = 0x214005c4

.field static final HAL_PROPID_HAZARD_WRITE:I = 0x214005c3

.field static final HAL_PROPID_HUD_BRIGHTNESS_MODE_READ:I = 0x214005a6

.field static final HAL_PROPID_HUD_BRIGHTNESS_READ:I = 0x214005a8

.field static final HAL_PROPID_HUD_HEIGHT_READ:I = 0x214005a4

.field static final HAL_PROPID_HUD_MODE_READ:I = 0x214005a2

.field static final HAL_PROPID_HUD_READ:I = 0x214005a0

.field static final HAL_PROPID_IPB_READ:I = 0x21400590

.field static final HAL_PROPID_IPB_WRITE:I = 0x2140058f

.field static final HAL_PROPID_LDP_MODE_CR2407_READ:I = 0x21400515

.field static final HAL_PROPID_LDP_MODE_READ:I = 0x21400385

.field static final HAL_PROPID_LHRDOOR_BUTTON_READ:I = 0x21400599

.field static final HAL_PROPID_MFS_SHAKE_7_READ:I = 0x214005b1

.field static final HAL_PROPID_NAV_DISPLAY_READ:I = 0x214005ae

.field static final HAL_PROPID_PASSENGER_SEAT_BACK_FR_READ:I = 0x2140047c

.field static final HAL_PROPID_PASSENGER_SEAT_BACK_FR_WRITE:I = 0x2140047b

.field static final HAL_PROPID_PASSENGER_SEAT_FR_READ:I = 0x2140047a

.field static final HAL_PROPID_PASSENGER_SEAT_FR_WRITE:I = 0x21400479

.field static final HAL_PROPID_PASSENGER_SEAT_LEG_FR_READ:I = 0x2140047e

.field static final HAL_PROPID_PASSENGER_SEAT_LEG_FR_WRITE:I = 0x2140047d

.field static final HAL_PROPID_PDOOR_BUTTON_READ:I = 0x21400598

.field static final HAL_PROPID_PM25_ATMOSPHERE_LIGHT_READ:I = 0x21400594

.field static final HAL_PROPID_PM25_ATMOSPHERE_LIGHT_WRITE:I = 0x21400593

.field static final HAL_PROPID_RADAR_WAOK_STS_READ:I = 0x21400368

.field static final HAL_PROPID_RHRDOOR_BUTTON_READ:I = 0x2140059a

.field static final HAL_PROPID_SOUND_OPTION_WRITE:I = 0x214004c8

.field static final HAL_PROPID_TANKS_TAB_READ:I = 0x21400940

.field static final HAL_PROPID_TJA_MODE_READ:I = 0x2140081b

.field static final HAL_PROPID_VC_EXT_VENDOR_APA_FAIL_READ:I = 0x214005b0

.field static final HAL_PROPID_VC_EXT_VENDOR_HOME_CONNECT_READ:I = 0x214005af

.field static final HAL_PROPID_VC_VENDOR_ADAS_AEB_READ:I = 0x21400401

.field static final HAL_PROPID_VC_VENDOR_ADAS_AEB_WRITE:I = 0x21400400

.field static final HAL_PROPID_VC_VENDOR_ADAS_BSD_READ:I = 0x21400421

.field static final HAL_PROPID_VC_VENDOR_ADAS_BSD_WRITE:I = 0x21400420

.field static final HAL_PROPID_VC_VENDOR_ADAS_DAI_READ:I = 0x2140040d

.field static final HAL_PROPID_VC_VENDOR_ADAS_DAI_WRITE:I = 0x2140040c

.field static final HAL_PROPID_VC_VENDOR_ADAS_DAI_ZDC_READ:I = 0x21400572

.field static final HAL_PROPID_VC_VENDOR_ADAS_DOW_READ:I = 0x21400423

.field static final HAL_PROPID_VC_VENDOR_ADAS_DOW_WRITE:I = 0x21400422

.field static final HAL_PROPID_VC_VENDOR_ADAS_DWD_READ:I = 0x2140041f

.field static final HAL_PROPID_VC_VENDOR_ADAS_DWD_WARNING_DISTANCE_READ:I = 0x214004a0

.field static final HAL_PROPID_VC_VENDOR_ADAS_DWD_WRITE:I = 0x2140041e

.field static final HAL_PROPID_VC_VENDOR_ADAS_ELK_READ:I = 0x2140041d

.field static final HAL_PROPID_VC_VENDOR_ADAS_ELK_WRITE:I = 0x2140041c

.field static final HAL_PROPID_VC_VENDOR_ADAS_ELK_ZDC_READ:I = 0x21400573

.field static final HAL_PROPID_VC_VENDOR_ADAS_FCW_ON_OFF_READ:I = 0x21400405

.field static final HAL_PROPID_VC_VENDOR_ADAS_FCW_ON_OFF_WRITE:I = 0x21400404

.field static final HAL_PROPID_VC_VENDOR_ADAS_FCW_SEN_READ:I = 0x21400403

.field static final HAL_PROPID_VC_VENDOR_ADAS_FCW_SEN_WRITE:I = 0x21400402

.field static final HAL_PROPID_VC_VENDOR_ADAS_IES_READ:I = 0x2140040f

.field static final HAL_PROPID_VC_VENDOR_ADAS_IES_WRITE:I = 0x2140040e

.field static final HAL_PROPID_VC_VENDOR_ADAS_IES_ZDC_READ:I = 0x2140056a

.field static final HAL_PROPID_VC_VENDOR_ADAS_IF_EXIT_READ:I = 0x21400407

.field static final HAL_PROPID_VC_VENDOR_ADAS_IF_EXIT_WRITE:I = 0x21400406

.field static final HAL_PROPID_VC_VENDOR_ADAS_IF_EXIT_ZDC_READ:I = 0x21400571

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDP_READ:I = 0x21400419

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDP_SEN_READ:I = 0x2140041b

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDP_SEN_WRITE:I = 0x2140041a

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDP_WRITE:I = 0x21400418

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDP_ZDC_READ:I = 0x21400569

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDW_READ:I = 0x21400415

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDW_WARN_READ:I = 0x21400417

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDW_WARN_WRITE:I = 0x21400416

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDW_WRITE:I = 0x21400414

.field static final HAL_PROPID_VC_VENDOR_ADAS_LDW_ZDC_READ:I = 0x21400568

.field static final HAL_PROPID_VC_VENDOR_ADAS_RCW_READ:I = 0x21400425

.field static final HAL_PROPID_VC_VENDOR_ADAS_RCW_WRITE:I = 0x21400424

.field static final HAL_PROPID_VC_VENDOR_ADAS_SCF_READ:I = 0x2140040b

.field static final HAL_PROPID_VC_VENDOR_ADAS_SCF_WRITE:I = 0x2140040a

.field static final HAL_PROPID_VC_VENDOR_ADAS_SLA_ON_OFF_READ:I = 0x21400409

.field static final HAL_PROPID_VC_VENDOR_ADAS_SLA_ON_OFF_WRITE:I = 0x21400408

.field static final HAL_PROPID_VC_VENDOR_ADAS_TLI_READ:I = 0x21400413

.field static final HAL_PROPID_VC_VENDOR_ADAS_TLI_WRITE:I = 0x21400412

.field static final HAL_PROPID_VC_VENDOR_ADAS_TSI_READ:I = 0x21400411

.field static final HAL_PROPID_VC_VENDOR_ADAS_TSI_WRITE:I = 0x21400410

.field static final HAL_PROPID_VC_VENDOR_AEB_DEC_READ:I = 0x21400391

.field static final HAL_PROPID_VC_VENDOR_AEB_T1P_READ:I = 0x214004db

.field static final HAL_PROPID_VC_VENDOR_AEB_T1P_WRITE:I = 0x214004dc

.field static final HAL_PROPID_VC_VENDOR_ATMOSPHERE_LIGHT_BRIGHTNESS_READ:I = 0x2140044c

.field static final HAL_PROPID_VC_VENDOR_ATMOSPHERE_LIGHT_BRIGHTNESS_WRITE:I = 0x2140044b

.field static final HAL_PROPID_VC_VENDOR_ATMOSPHERE_LIGHT_COLOR_READ:I = 0x2140044e

.field static final HAL_PROPID_VC_VENDOR_ATMOSPHERE_LIGHT_COLOR_WRITE:I = 0x2140044d

.field static final HAL_PROPID_VC_VENDOR_ATMOSPHERE_LIGHT_READ:I = 0x2140044a

.field static final HAL_PROPID_VC_VENDOR_ATMOSPHERE_LIGHT_STATIC_LIGHT_COLOR_READ:I = 0x21400583

.field static final HAL_PROPID_VC_VENDOR_ATMOSPHERE_LIGHT_STATIC_LIGHT_COLOR_WRITE:I = 0x21400582

.field static final HAL_PROPID_VC_VENDOR_ATMOSPHERE_LIGHT_WRITE:I = 0x21400449

.field static final HAL_PROPID_VC_VENDOR_AUTOLOCK_READ:I = 0x2140045d

.field static final HAL_PROPID_VC_VENDOR_AUTOLOCK_WRITE:I = 0x2140045c

.field static final HAL_PROPID_VC_VENDOR_AUTOUNLOCK_READ:I = 0x2140045f

.field static final HAL_PROPID_VC_VENDOR_AUTOUNLOCK_WRITE:I = 0x2140045e

.field static final HAL_PROPID_VC_VENDOR_AVH_READ:I = 0x2140042f

.field static final HAL_PROPID_VC_VENDOR_AVH_WRITE:I = 0x2140042e

.field static final HAL_PROPID_VC_VENDOR_BLINK_NO_READ:I = 0x21400494

.field static final HAL_PROPID_VC_VENDOR_BLINK_NO_WRITE:I = 0x21400493

.field static final HAL_PROPID_VC_VENDOR_BRAKE_LIGHT_READ:I = 0x21400902

.field static final HAL_PROPID_VC_VENDOR_CHILD_LOCK_READ:I = 0x2140038f

.field static final HAL_PROPID_VC_VENDOR_CHILD_LOCK_WRITE:I = 0x2140046b

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_AIRBAG_FAIL_READ:I = 0x21400390

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_APA_WRITE:I = 0x21400926

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_AVM_ATCM_READ:I = 0x21400928

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_AVM_REQ_RESULT_READ:I = 0x21400922

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_HAZARD_LIGHT_READ:I = 0x21400392

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_LATERA_ACCALELERATION_READ:I = 0x216004b3

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_LH_TURN_LIGHT_READ:I = 0x2140022a

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_LONGITUDINAL_ACCALELERATION_READ:I = 0x21601239

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_RH_TURN_LIGHT_READ:I = 0x2140022b

.field static final HAL_PROPID_VC_VENDOR_CLUSTER_TAIL_LIGHT_READ:I = 0x21400125

.field static final HAL_PROPID_VC_VENDOR_COOL_WRITE:I = 0x2140046a

.field static final HAL_PROPID_VC_VENDOR_CURVE_DEC_READ:I = 0x214004d6

.field static final HAL_PROPID_VC_VENDOR_CURVE_DEC_WRITE:I = 0x214004d7

.field static final HAL_PROPID_VC_VENDOR_DCLC_ZDC_READ:I = 0x21400570

.field static final HAL_PROPID_VC_VENDOR_DCLC_ZDC_WRITE:I = 0x2140056f

.field static final HAL_PROPID_VC_VENDOR_DISTANCE_WARNING_T1P_READ:I = 0x214004f4

.field static final HAL_PROPID_VC_VENDOR_DISTANCE_WARNING_T1P_WRITE:I = 0x214004f5

.field static final HAL_PROPID_VC_VENDOR_DISTRACTION_LEVEL_WRITE:I = 0x214004d9

.field static final HAL_PROPID_VC_VENDOR_DMS_READ:I = 0x21400454

.field static final HAL_PROPID_VC_VENDOR_DMS_WRITE:I = 0x21400453

.field static final HAL_PROPID_VC_VENDOR_DRIVER_LIGHT_READ:I = 0x21400801

.field static final HAL_PROPID_VC_VENDOR_DRIVER_LUMBART_FR_READ:I = 0x21400476

.field static final HAL_PROPID_VC_VENDOR_DRIVER_LUMBART_FR_WRITE:I = 0x21400475

.field static final HAL_PROPID_VC_VENDOR_DRIVER_LUMBART_UD_READ:I = 0x21400478

.field static final HAL_PROPID_VC_VENDOR_DRIVER_LUMBART_UD_WRITE:I = 0x21400477

.field static final HAL_PROPID_VC_VENDOR_DRIVER_SEATF_UD_READ:I = 0x21400472

.field static final HAL_PROPID_VC_VENDOR_DRIVER_SEATF_UD_WRITE:I = 0x21400471

.field static final HAL_PROPID_VC_VENDOR_DRIVER_SEATR_UD_READ:I = 0x21400474

.field static final HAL_PROPID_VC_VENDOR_DRIVER_SEATR_UD_WRITE:I = 0x21400473

.field static final HAL_PROPID_VC_VENDOR_DRIVER_SEAT_BACK_FR_READ:I = 0x21400470

.field static final HAL_PROPID_VC_VENDOR_DRIVER_SEAT_BACK_FR_WRITE:I = 0x2140046f

.field static final HAL_PROPID_VC_VENDOR_DRIVER_SEAT_FR_READ:I = 0x2140046e

.field static final HAL_PROPID_VC_VENDOR_DRIVER_SEAT_FR_WRITE:I = 0x2140046d

.field static final HAL_PROPID_VC_VENDOR_DRIVE_MODE_READ:I = -0x1

.field static final HAL_PROPID_VC_VENDOR_DRIVE_MODE_WRITE:I = 0x21400426

.field static final HAL_PROPID_VC_VENDOR_EPS_DRIVER_MODE_READ:I = 0x2140048e

.field static final HAL_PROPID_VC_VENDOR_EPS_DRIVER_MODE_WRITE:I = 0x2140048d

.field static final HAL_PROPID_VC_VENDOR_EPS_MODE_PHEV_READ:I = 0x21400581

.field static final HAL_PROPID_VC_VENDOR_EPS_MODE_READ:I = 0x21400218

.field static final HAL_PROPID_VC_VENDOR_EPS_MODE_WRITE:I = 0x2140048b

.field static final HAL_PROPID_VC_VENDOR_ESP_READ:I = 0x2140042b

.field static final HAL_PROPID_VC_VENDOR_ESP_WRITE:I = 0x2140042a

.field static final HAL_PROPID_VC_VENDOR_FATIGUE_DRIVE_WRITE:I = 0x214004da

.field static final HAL_PROPID_VC_VENDOR_FCW_ON_T1P_READ:I = 0x214004df

.field static final HAL_PROPID_VC_VENDOR_FCW_ON_T1P_WRITE:I = 0x214004f0

.field static final HAL_PROPID_VC_VENDOR_FCW_OPTION_T1P_READ:I = 0x214004dd

.field static final HAL_PROPID_VC_VENDOR_FCW_OPTION_T1P_WRITE:I = 0x214004de

.field static final HAL_PROPID_VC_VENDOR_FL_WINDOW_READ:I = 0x2140043c

.field static final HAL_PROPID_VC_VENDOR_FL_WINDOW_WRITE:I = 0x2140043b

.field static final HAL_PROPID_VC_VENDOR_FOLLOW_ME_HOME_READ:I = 0x21400492

.field static final HAL_PROPID_VC_VENDOR_FOLLOW_ME_HOME_WRITE:I = 0x21400491

.field static final HAL_PROPID_VC_VENDOR_FRONT_FOG_LIGHT_CONTROL_READ:I = 0x21400802

.field static final HAL_PROPID_VC_VENDOR_FRONT_FOG_LIGHT_CONTROL_WRITE:I = 0x2140058c

.field static final HAL_PROPID_VC_VENDOR_FR_WINDOW_READ:I = 0x2140043e

.field static final HAL_PROPID_VC_VENDOR_FR_WINDOW_WRITE:I = 0x2140043d

.field static final HAL_PROPID_VC_VENDOR_HDC_READ:I = 0x2140042d

.field static final HAL_PROPID_VC_VENDOR_HDC_WRITE:I = 0x2140042c

.field static final HAL_PROPID_VC_VENDOR_HIGH_BEAM_READ:I = 0x214004c0

.field static final HAL_PROPID_VC_VENDOR_HMA_ON_READ:I = 0x21400498

.field static final HAL_PROPID_VC_VENDOR_HMA_ON_WRITE:I = 0x21400497

.field static final HAL_PROPID_VC_VENDOR_HMA_READ:I = 0x21400496

.field static final HAL_PROPID_VC_VENDOR_HMA_WRITE:I = 0x21400495

.field static final HAL_PROPID_VC_VENDOR_ISS_READ:I = 0x2140049a

.field static final HAL_PROPID_VC_VENDOR_ISS_WRITE:I = 0x21400499

.field static final HAL_PROPID_VC_VENDOR_KEY_READ:I = 0x2140011a

.field static final HAL_PROPID_VC_VENDOR_LDW_SEN_T1P_READ:I = 0x214004fa

.field static final HAL_PROPID_VC_VENDOR_LDW_SEN_T1P_WRITE:I = 0x214004fb

.field static final HAL_PROPID_VC_VENDOR_LDW_T1P_READ:I = 0x21400835

.field static final HAL_PROPID_VC_VENDOR_LDW_T1P_WRITE:I = 0x21400839

.field static final HAL_PROPID_VC_VENDOR_LH_TURN_LIGHT_READ:I = 0x214004bd

.field static final HAL_PROPID_VC_VENDOR_LIGHT_CONTROL_WRITE:I = 0x21400585

.field static final HAL_PROPID_VC_VENDOR_LIGHT_HEIGHT_READ:I = 0x21400490

.field static final HAL_PROPID_VC_VENDOR_LIGHT_HEIGHT_WRITE:I = 0x2140048f

.field static final HAL_PROPID_VC_VENDOR_LOW_BEAM_READ:I = 0x214004bf

.field static final HAL_PROPID_VC_VENDOR_LOW_BEAM_T1K_READ:I = 0x21400904

.field static final HAL_PROPID_VC_VENDOR_MFS_HEAT_READ:I = 0x21400488

.field static final HAL_PROPID_VC_VENDOR_MFS_HEAT_WRITE:I = 0x21400487

.field static final HAL_PROPID_VC_VENDOR_MFS_SHAKE_READ:I = 0x2140048a

.field static final HAL_PROPID_VC_VENDOR_MFS_SHAKE_WRITE:I = 0x21400489

.field static final HAL_PROPID_VC_VENDOR_MIRROR_DRIVER_READ:I = 0x2140043a

.field static final HAL_PROPID_VC_VENDOR_MIRROR_DRIVER_WRITE:I = 0x21400439

.field static final HAL_PROPID_VC_VENDOR_MIRROR_FLIP_READ:I = 0x21400433

.field static final HAL_PROPID_VC_VENDOR_MIRROR_FLIP_T1K_READ:I = 0x21400587

.field static final HAL_PROPID_VC_VENDOR_MIRROR_FLIP_WRITE:I = 0x21400432

.field static final HAL_PROPID_VC_VENDOR_MIRROR_HOLD_READ:I = 0x214004a1

.field static final HAL_PROPID_VC_VENDOR_MIRROR_HOLD_SWITCH_READ:I = 0x21400431

.field static final HAL_PROPID_VC_VENDOR_MIRROR_HOLD_SWITCH_WRITE:I = 0x21400434

.field static final HAL_PROPID_VC_VENDOR_MIRROR_HOLD_WRITE:I = 0x21400430

.field static final HAL_PROPID_VC_VENDOR_MIRROR_LEFT_READ:I = 0x21400436

.field static final HAL_PROPID_VC_VENDOR_MIRROR_LEFT_WRITE:I = 0x21400435

.field static final HAL_PROPID_VC_VENDOR_MIRROR_RIGHT_READ:I = 0x21400438

.field static final HAL_PROPID_VC_VENDOR_MIRROR_RIGHT_WRITE:I = 0x21400437

.field static final HAL_PROPID_VC_VENDOR_MUSIC_LOUDNESS_1000HZ_WRITE:I = 0x21400458

.field static final HAL_PROPID_VC_VENDOR_MUSIC_LOUDNESS_120HZ_WRITE:I = 0x21400455

.field static final HAL_PROPID_VC_VENDOR_MUSIC_LOUDNESS_1500HZ_WRITE:I = 0x21400459

.field static final HAL_PROPID_VC_VENDOR_MUSIC_LOUDNESS_2000HZ_WRITE:I = 0x2140045a

.field static final HAL_PROPID_VC_VENDOR_MUSIC_LOUDNESS_250HZ_WRITE:I = 0x21400456

.field static final HAL_PROPID_VC_VENDOR_MUSIC_LOUDNESS_500HZ_WRITE:I = 0x21400457

.field static final HAL_PROPID_VC_VENDOR_MUSIC_LOUDNESS_6000HZ_WRITE:I = 0x2140045b

.field static final HAL_PROPID_VC_VENDOR_MUSIC_READ:I = 0x21400452

.field static final HAL_PROPID_VC_VENDOR_MUSIC_WRITE:I = 0x21400451

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_MASSAGE_INTENSITY_READ:I = 0x21400482

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_MASSAGE_INTENSITY_WRITE:I = 0x21400481

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_MASSAGE_MODE_READ:I = 0x21400484

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_MASSAGE_MODE_WRITE:I = 0x21400483

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_MASSAGE_READ:I = 0x21400480

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_MASSAGE_WRITE:I = 0x2140047f

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_MIRROR_LOCATION_READ:I = 0x214004c1

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_MIRROR_LOCATION_WRITE:I = 0x21400485

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_SEAT_BACK_FR_READ:I = 0x214004c3

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_SEAT_BACK_FR_WRITE:I = -0x1

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_SEAT_FR_READ:I = 0x214004c2

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_SEAT_FR_WRITE:I = -0x1

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_SEAT_LEG_FR_READ:I = 0x214004c4

.field static final HAL_PROPID_VC_VENDOR_PASSENGER_SEAT_LEG_FR_WRITE:I = -0x1

.field static final HAL_PROPID_VC_VENDOR_PAS_READ:I = 0x21400469

.field static final HAL_PROPID_VC_VENDOR_PAS_WRITE:I = 0x21400468

.field static final HAL_PROPID_VC_VENDOR_PAS_ZDC_READ:I = 0x21400575

.field static final HAL_PROPID_VC_VENDOR_PAS_ZDC_WRITE:I = 0x21400574

.field static final HAL_PROPID_VC_VENDOR_PHEV_HV_READ:I = 0x214004bc

.field static final HAL_PROPID_VC_VENDOR_PHEV_POWER_DISTANCE_READ:I = 0x21600206

.field static final HAL_PROPID_VC_VENDOR_PHEV_POWER_MODE_READ:I = 0x214002a9

.field static final HAL_PROPID_VC_VENDOR_PHEV_POWER_MODE_WRITE:I = 0x214004ba

.field static final HAL_PROPID_VC_VENDOR_PHEV_PT_READY_READ:I = 0x21400227

.field static final HAL_PROPID_VC_VENDOR_PHEV_REGEBERATE_LEVEL_READ:I = 0x21400229

.field static final HAL_PROPID_VC_VENDOR_PHEV_REGEBERATE_LEVEL_WRITE:I = 0x214004bb

.field static final HAL_PROPID_VC_VENDOR_POWER_ALARM_MODE_READ:I = 0x21400127

.field static final HAL_PROPID_VC_VENDOR_RCTB_ZDC_READ:I = 0x2140056c

.field static final HAL_PROPID_VC_VENDOR_RCTB_ZDC_WRITE:I = 0x2140056b

.field static final HAL_PROPID_VC_VENDOR_RCW_ZDC_READ:I = 0x2140056e

.field static final HAL_PROPID_VC_VENDOR_RCW_ZDC_WRITE:I = 0x2140056d

.field static final HAL_PROPID_VC_VENDOR_REAR_FOG_LIGHT_CONTROL_READ:I = 0x21400803

.field static final HAL_PROPID_VC_VENDOR_REAR_FOG_LIGHT_CONTROL_WRITE:I = 0x21400586

.field static final HAL_PROPID_VC_VENDOR_REAR_WIPER_READ:I = 0x21400467

.field static final HAL_PROPID_VC_VENDOR_REAR_WIPER_WRITE:I = 0x21400466

.field static final HAL_PROPID_VC_VENDOR_REMOTELOCK_READ:I = 0x21400461

.field static final HAL_PROPID_VC_VENDOR_REMOTELOCK_WRITE:I = 0x21400460

.field static final HAL_PROPID_VC_VENDOR_RH_TURN_LIGHT_READ:I = 0x214004be

.field static final HAL_PROPID_VC_VENDOR_RL_WINDOW_READ:I = 0x21400440

.field static final HAL_PROPID_VC_VENDOR_RL_WINDOW_WRITE:I = 0x2140043f

.field static final HAL_PROPID_VC_VENDOR_RR_WINDOW_READ:I = 0x21400442

.field static final HAL_PROPID_VC_VENDOR_RR_WINDOW_WRITE:I = 0x21400441

.field static final HAL_PROPID_VC_VENDOR_SCENE_CO_ERR_READ:I = 0x214004a9

.field static final HAL_PROPID_VC_VENDOR_SCENE_CO_STS_READ:I = 0x214004a8

.field static final HAL_PROPID_VC_VENDOR_SCENE_DRIVER_DOOR_READ:I = 0x214004a4

.field static final HAL_PROPID_VC_VENDOR_SCENE_EMS_ENGINE_STS_READ:I = 0x214004af

.field static final HAL_PROPID_VC_VENDOR_SCENE_ENGINE_READ:I = 0x214004a3

.field static final HAL_PROPID_VC_VENDOR_SCENE_KEY_READ:I = 0x214004a2

.field static final HAL_PROPID_VC_VENDOR_SCENE_LIGHT_SHOW_READ:I = 0x214004ae

.field static final HAL_PROPID_VC_VENDOR_SCENE_LR_DOOR_READ:I = 0x214004a7

.field static final HAL_PROPID_VC_VENDOR_SCENE_PASSENGER_DOOR_READ:I = 0x214004a5

.field static final HAL_PROPID_VC_VENDOR_SCENE_PM25_STS_READ:I = 0x214004b0

.field static final HAL_PROPID_VC_VENDOR_SCENE_POWER_LIMIT_READ:I = 0x214004ad

.field static final HAL_PROPID_VC_VENDOR_SCENE_RANDOM_SHOW_MODE_WRITE:I = 0x214004ac

.field static final HAL_PROPID_VC_VENDOR_SCENE_RR_DOOR_READ:I = 0x214004a6

.field static final HAL_PROPID_VC_VENDOR_SCENE_SHOW_MODE_WRITE:I = 0x214004ab

.field static final HAL_PROPID_VC_VENDOR_SCENE_SMART_MODE_WRITE:I = 0x214004aa

.field static final HAL_PROPID_VC_VENDOR_SKYLIGHT_PERCENTAGE_READ:I = 0x21400446

.field static final HAL_PROPID_VC_VENDOR_SKYLIGHT_PERCENTAGE_WRITE:I = 0x21400445

.field static final HAL_PROPID_VC_VENDOR_SKYLIGHT_READ:I = 0x21400444

.field static final HAL_PROPID_VC_VENDOR_SKYLIGHT_WRITE:I = 0x21400443

.field static final HAL_PROPID_VC_VENDOR_SLA_T1P_READ:I = 0x21400836

.field static final HAL_PROPID_VC_VENDOR_SLA_T1P_WRITE:I = 0x214004f1

.field static final HAL_PROPID_VC_VENDOR_SOC_MANAGE_READ:I = 0x21400825

.field static final HAL_PROPID_VC_VENDOR_SOC_MANAGE_WRITE:I = 0x214004d8

.field static final HAL_PROPID_VC_VENDOR_STATIC_MODE_READ:I = 0x21400450

.field static final HAL_PROPID_VC_VENDOR_STATIC_MODE_WRITE:I = 0x2140044f

.field static final HAL_PROPID_VC_VENDOR_STEER_ANGLE_READ:I = 0x21600905

.field static final HAL_PROPID_VC_VENDOR_SUNSHADE_READ:I = 0x21400448

.field static final HAL_PROPID_VC_VENDOR_SUNSHADE_WRITE:I = 0x21400447

.field static final HAL_PROPID_VC_VENDOR_TIRE_LF_PRESSURE_READ:I = 0x216002b3

.field static final HAL_PROPID_VC_VENDOR_TIRE_LR_PRESSURE_READ:I = 0x216002b5

.field static final HAL_PROPID_VC_VENDOR_TIRE_POSTION_READ:I = 0x214002b1

.field static final HAL_PROPID_VC_VENDOR_TIRE_PRESSURE_WARNING_LF_READ:I = 0x214002dd

.field static final HAL_PROPID_VC_VENDOR_TIRE_PRESSURE_WARNING_LR_READ:I = 0x214002af

.field static final HAL_PROPID_VC_VENDOR_TIRE_PRESSURE_WARNING_RF_READ:I = 0x214002ae

.field static final HAL_PROPID_VC_VENDOR_TIRE_PRESSURE_WARNING_RR_READ:I = 0x214002b0

.field static final HAL_PROPID_VC_VENDOR_TIRE_RF_PRESSURE_READ:I = 0x216002b4

.field static final HAL_PROPID_VC_VENDOR_TIRE_RR_PRESSURE_READ:I = 0x216002b6

.field static final HAL_PROPID_VC_VENDOR_TIRE_TEMPERATURE_READ:I = 0x214002b2

.field static final HAL_PROPID_VC_VENDOR_TJA_T1P_READ:I = 0x214004f2

.field static final HAL_PROPID_VC_VENDOR_TJA_T1P_WRITE:I = 0x214004f3

.field static final HAL_PROPID_VC_VENDOR_USER_ID_WRITE:I = 0x214002dc

.field static final HAL_PROPID_VC_VENDOR_VOICE_WAKE_WRITE:I = 0x21400567

.field static final HAL_PROPID_VC_VENDOR_WELCOME_FL_READ:I = 0x21400465

.field static final HAL_PROPID_VC_VENDOR_WELCOME_FL_WRITE:I = 0x21400464

.field static final HAL_PROPID_VC_VENDOR_WELCOME_PASSENGER_READ:I = 0x214004b5

.field static final HAL_PROPID_VC_VENDOR_WELCOME_PASSENGER_WRITE:I = 0x214004b4

.field static final HAL_PROPID_VC_VENDOR_WELCOME_READ:I = 0x21400463

.field static final HAL_PROPID_VC_VENDOR_WELCOME_WRITE:I = 0x21400462

.field static final HAL_PROPID_VC_VENDOR_WIRELESS_CHARGING_STS_READ:I = 0x214004b1

.field static final HAL_PROPID_VC_VENDOR_WIRELESS_ENTER_SFCHARGE_READ:I = 0x214004b2

.field static final HAL_PROPID_VC_VENDOR_X_MODE_READ:I = -0x1

.field static final HAL_PROPID_VC_VENDOR_X_MODE_WRITE:I = -0x1

.field static final HAL_PROPID_WELCOME_SOUND_WRITE:I = 0x214004c6

.field static final HAL_PROPID_WINDOW_INHIBIT_READ:I = 0x214004e4

.field static final HAL_PROPID_WIPER_MODE_READ:I = 0x21400597

.field static final HAL_PROPID_WIPER_MODE_WRITE:I = 0x21400596

.field static final HAL_PROPID_WIPER_SEN_WRITE:I = 0x21400595


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 5
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
